// 1st group member
// Name: Hussain Ali Kadhem Kadhem
// ID: 202302274
// Section: 5

// 2nd group member
// Name: Ali Al Ridha Salim
// ID: 202304993
// Section: 5
import java.util.ArrayList;
public class Patient {
    //NOTE: setters, getters and the constructors were generated by the IntelliJ built in generator.

    //<<DATA MEMBERS>>==================================================================================================
    private long patientId;
    private String firstName;
    private String lastName;
    private char gender;
    private String email;
    private ArrayList<String> medicalHistory;
    private ArrayList<Service> servicesReceived;

    //<<CONSTRUCTORS>>==================================================================================================
    public Patient(long patientId, String firstName, String lastName, char gender, String email) {
        this.patientId = patientId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        medicalHistory=new ArrayList<>();
        servicesReceived=new ArrayList<>();

    }
    public Patient() {
        medicalHistory=new ArrayList<>();
        servicesReceived=new ArrayList<>();
        patientId=0;
        firstName=null;
        lastName=null;
        email=null;
        gender=0;

    }

    //<<SET METHODS>>===================================================================================================
    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setMedicalHisatory(ArrayList<String> medicalHisatory) {
        this.medicalHistory = medicalHisatory;
    }

    public void setServicesReceived(ArrayList<Service> servicesReceived) {
        this.servicesReceived = servicesReceived;
    }

    //<<GET METHODS>>==================================================================================================

    public long getPatientId() {
        return patientId;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public char getGender() {
        return gender;
    }

    public String getEmail() {
        return email;
    }

    public ArrayList<String> getMedicalHisatory() {
        return medicalHistory;
    }

    public ArrayList<Service> getServicesReceived() {
        return servicesReceived;
    }

    //<<equals method>>=================================================================================================
    public boolean equals(Patient a){
        return(a.getPatientId()==getPatientId());
    }

    //<<PRINTING METHODS>>==============================================================================================
    //printMedicalHistory: a method to print the content of the medicalHistory list.
    public void printMedicalHistory(){
        System.out.println("Medical History");
        System.out.println("===========================================================================");
        if(medicalHistory.size()==0){
            System.out.println("This patient does not have a medical history");
            System.out.println();
            System.out.println();
        return;
        }
        for (int i = 0; i < medicalHistory.size(); i++) {
            System.out.println((i+1)+". "+ medicalHistory.get(i));

        }
        System.out.println();
        System.out.println();
    }

    //printServiceReceived: a method to print the content of the servicesReceived list.
    public void printServicesReceived(){
        System.out.println("Services");
        System.out.println("===========================================================================");
        if(servicesReceived.size()==0){
            System.out.println("No services were registered");
            System.out.println();
            System.out.println();
            return;
        }
        for (int i = 0; i < servicesReceived.size(); i++) {
            System.out.println((i+1)+". "+ servicesReceived.get(i));

        }
        System.out.println();
        System.out.println();
    }

    //toString: a method to return a String value containing patient information.
    public String toString(){

        String str="Patient Details: \n" +
                "Patient Id:  "+getPatientId()+"\n" +
                "First name: "+getFirstName()+"\n" +
                "Last name: "+getLastName()+"\n" +
                "Gender: "+getGender()+"\n" +
                "Email: "+getEmail()+"\n";

        return str;
    }

}
