// 1st group member
// Name: Hussain Ali Kadhem Kadhem
// ID: 202302274
// Section: 5

// 2nd group member
// Name: Ali Al Ridha Salim
// ID: 202304993
// Section: 5
import java.util.Objects;

public class Service {

    //NOTE: setters, getters, constructors and the equals method were generated by the IntelliJ built in generator.

    //<<DATA MEMBERS >>=================================================================================================
    private String serviceId;
    private String serviceName;
    private double cost;
    private int duration;

    //<<CONSTRUCTORS >>=================================================================================================
    public Service()
    {
        serviceId=null;
        serviceName=null;
        cost=0;
        duration=0;
    }

    public Service(String serviceId, String serviceName, double cost, int duration)
    {
        this.serviceId = serviceId;
        this.serviceName = serviceName;
        this.cost = cost;
        this.duration = duration;
    }
    //<<GET METHODS>>===================================================================================================
    public String getServiceId() {
        return serviceId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public double getCost() {
        return cost;
    }

    public int getDuration() {
        return duration;
    }

    //<<SET METHODS >>==================================================================================================

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    //<<EQUALS METHOD>>=================================================================================================
    //equals: Generated by IntelliJ. The method compares two objects of type Service.
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Service service = (Service) o;
        return Double.compare(cost, service.cost) == 0 && duration == service.duration && Objects.equals(serviceId, service.serviceId) && Objects.equals(serviceName, service.serviceName);
    }

    //<<toString METHOD>>===============================================================================================
    //toString: a method to return a String value containing service information.
    public String toString(){

        String str="Service Details: \n" +
                "Service Id:  "+getServiceId()+"\n" +
                "Service name: "+getServiceName()+"\n" +
                "Service cost: "+getCost()+"\n" +
                "Service duration: "+getDuration()+" minutes\n";

return str;
    }



}
